apiVersion: v1
kind: Pod
metadata:
  name: my-html-pod
  labels:
    app: my-html-pod
spec:
  containers:
    - name: my-html-container
      image: deepthihp2/my-html-page
      ports:
        - containerPort: 80
