apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  lables:
    app: ex1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
# Assessment:-
# 1) Write a yaml file to create a pod and check how to access nginx using localhost.
#    kubectl apply -f pod.yaml
#    kubectl port-forward nginx-k8s 8080:80
